import { CaseRecord } from '@/types';

export const SAMPLE_CASES: CaseRecord[] = [
  {
    id: 'case-sample-1',
    case_code: 'CAS-2026-1042',
    created_at: '2026-09-27T08:15:00Z',
    full_name: 'Carlos Alberto Mora Vargas',
    phone: '87123456',
    email: 'carlos.mora.cr@ejemplo.com',
    institution: 'CCSS - Hospital Rafael Ángel Calderón Guardia',
    description: 'Tengo 1 año y 8 meses esperando fecha de cirugía de reemplazo de rodilla. Mi condición ha empeorado notablemente y ya casi no puedo caminar sin apoyo. En la clínica me dicen que no hay ortopedistas disponibles.',
    privacy_accepted: true,
    appointment_requested: true,
    preferred_date: '2026-10-02',
    preferred_time_slot: 'manana',
    status: 'nuevo',
    internal_notes: 'Paciente aportó dictamen médico de especialista privado donde consta riesgo de inmovilidad.',
    files: [
      {
        id: 'file-1',
        case_id: 'case-sample-1',
        file_name: 'dictamen-ortopedia-set2026.pdf',
        file_path: 'case-sample-1/dictamen.pdf',
        file_size: 2450000,
        mime_type: 'application/pdf',
        created_at: '2026-09-27T08:15:00Z',
      },
    ],
    notes: [
      {
        id: 'note-1',
        case_id: 'case-sample-1',
        author_email: 'admin@atlanticayasociados.com',
        content: 'Caso con alta viabilidad para amparo ante Sala IV por derecho a la salud. Procederemos a redactar intimación a la Dirección Médica.',
        created_at: '2026-09-27T09:30:00Z',
      },
    ],
  },
  {
    id: 'case-sample-2',
    case_code: 'CAS-2026-1088',
    created_at: '2026-09-26T14:40:00Z',
    full_name: 'Lorena Jiménez Fallas',
    phone: '61459980',
    email: 'lorena.jimen@ejemplo.com',
    institution: 'Municipalidad de Pococí',
    description: 'La alcantarilla principal frente a nuestra calle comunal en Guápiles se desbordó hace 3 meses con las lluvias. Presentamos una carta firmada por 14 vecinos y en la Unidad Técnica no nos dan razón ni contestan el correo.',
    privacy_accepted: true,
    appointment_requested: false,
    status: 'en_analisis',
    internal_notes: 'Plazo de 10 días hábiles vencido con creces. Procede memorial con citación del Art. 27.',
    files: [
      {
        id: 'file-2',
        case_id: 'case-sample-2',
        file_name: 'carta-vecinos-sello-recibido.jpg',
        file_path: 'case-sample-2/carta.jpg',
        file_size: 1850000,
        mime_type: 'image/jpeg',
        created_at: '2026-09-26T14:40:00Z',
      },
    ],
  },
  {
    id: 'case-sample-3',
    case_code: 'CAS-2026-1120',
    created_at: '2026-09-24T10:10:00Z',
    full_name: 'Minor Quesada Rojas',
    phone: '83901122',
    email: null,
    institution: 'Casa Presidencial / Despacho de Atención Ciudadana',
    description: 'Solicitud colectiva de revisión del estado de abandono del puente vecinal que conecta a tres comunidades rurales. Requerimos formular un documento de alto impacto para la Dirección de Gestión Presidencial.',
    privacy_accepted: true,
    appointment_requested: true,
    preferred_date: '2026-10-05',
    preferred_time_slot: 'tarde',
    status: 'en_proceso',
    internal_notes: 'Borrador de memorial en revisión con el solicitante vía WhatsApp.',
    files: [],
  },
];
